services:
  - type: web
    name: smp-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
